# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none
relative_permalinks: true

# Setup
title:               "SX:Archipelagos"
tagline:             ''
description:         'A Small Axe Journal of Caribbean New Media and Digital Humanities.'
url:                 http://smallaxe.net/
baseurl:             ''

# About/contact
author:
  name:              "SX:Archipelagos"
  email:             archipelagos@smallaxe.net

# Custom vars
version:             0.0.1
