# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none

# Setup
title:               "sx archipelagos"
tagline:             ''
description:         'a Small Axe journal of digital practice'
url:                 http://smallaxe.net/
baseurl:             ''

collections:
  issue01:
    output: true
    number: 1
    date: "Summer 2016"
    title: "Inaugural Issue"
    editors:
    - Kaiama Glover
    - Alex Gil
    - Kelly Josephs
    production:
    - Alex Gil
    - Dennis Tenen
    - Brian Ballsun-Stanton
  issue02:
    output: true
    number: 2
    date: "Summer 2017"
    title: "Second Issue"
    editors:
    - Kaiama Glover
    - Alex Gil
    production:
    - Alex Gil
    - Dennis Tenen
    - Brian Ballsun-Stanton
  archives:
    output: true

# Jekyll-Kramdown
markdown: kramdown

pandoc:
  extensions:
    - normalize
    - smart
    - csl: _styles/chicago.csl
    - bibliography: bibliography/references.bib

# Gems
# gems:
#   - jekyll-pandoc


# About/contact
author:
  name:              "SX:Archipelagos"
  email:             archipelagos@smallaxe.net

# Custom vars
version:             0.0.1

# Excluded
exclude: [utility]
